spring:
  application:
    name: fooberry-graphql-api
  servlet:
    multipart:
      enabled: true
      location: /tmp
server:
  port: 9000
  management:
    endpoints:
      web:
        exposure:
          include: health, info, metrics

# Taken mostly (for now entirely) from https://github.com/graphql-java-kickstart/graphql-spring-boot
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    cors:
      allowed-origins: http://some.domain.com
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
    # tracing-enabled: metrics-only
    # actuator-metrics: true
  annotations:
    base-package: org.rimple.fooberry.graphqlapi # required
    always-prettify: true #true is the default value, no need to specify it
  tools:
    schema-location-pattern: "**/*.graphqls"
    # Enable or disable the introspection query. Disabling it puts your server in contravention of the GraphQL
    # specification and expectations of most clients, so use this option with caution
    introspection-enabled: true

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.13.0
  props:
    resources:
      # query: query.graphql
      # defaultQuery: defaultQuery.graphql
      # variables: variables.graphql
    variables:
      editorTheme: "solarized light"
  # headers:
  # Authorization: "Bearer <your-token>"

altair:
  mapping: /altair
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    basePath: /
  enabled: true
  pageTitle: Altair
  cdn:
    enabled: false
    version: 2.1.7
  props:
    resources:
      # defaultQuery: defaultQuery.graphql
      # variables: variables.graphql
  headers:
    Authorization: "Bearer <your-token>"

graphql.playground:
  mapping: /playground
  endpoint: /graphql
  subscriptionEndpoint: /subscriptions
  staticPath.base: my-playground-resources-folder
  enabled: true
  pageTitle: Playground
  cdn:
    enabled: false
    version: latest
  settings:
    editor.cursorShape: line
    editor.fontFamily: "'Source Code Pro', 'Consolas', 'Inconsolata', 'Droid Sans Mono', 'Monaco', monospace"
    editor.fontSize: 14
    editor.reuseHeaders: true
    editor.theme: dark
    general.betaUpdates: false
    prettier.printWidth: 80
    prettier.tabWidth: 2
    prettier.useTabs: false
    request.credentials: omit
    schema.polling.enable: true
    schema.polling.endpointFilter: "*localhost*"
    schema.polling.interval: 2000
    schema.disableComments: true
    tracing.hideTracingResponse: true

logging:
  level:
    root: INFO
    graphql: TRACE
