graphql:
    servlet:
        mapping: /graphql
        enabled: true
        corsEnabled: true
        cors:
            allowed-origins: http://some.domain.com
        # if you want to @ExceptionHandler annotation for custom GraphQLErrors
        exception-handlers-enabled: true
        contextSetting: PER_REQUEST_WITH_INSTRUMENTATION