AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Fooberry Layers and Lambdas

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LambdaAPI:
    Type: AWS::Serverless::HttpApi
        
  AwsServices:
      Type: AWS::Serverless::LayerVersion
      Properties:
        LayerName: fooberry-node-layer
        Description: Layer for managing AWS Services for the Fooberry game
        ContentUri: ./lambda-layers
        CompatibleRuntimes:
          - nodejs12.x
        LicenseInfo: APACHE2
        RetentionPolicy: Retain

  AddGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      FunctionName: 'create-game-lambda'
      Description: 'Create game Lambda function'
      CodeUri: lambdas/functions/db/create-game
      Policies:
        - Statement:
          - Effect: "Allow"
            Action:
              - 'lambda:GetLayerVersion'
            Resource:
              - !Sub 'arn:aws:lambda:*:${AWS::AccountId}:layer:*:*'
      Events:
        CreateGame:
          Type: HttpApi
          Properties:
            ApiId: !Ref LambdaAPI
            Method: POST
            Path: /create-game
      Layers:
        - !Ref AwsServices

  UpdateGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      FunctionName: 'update-game-lambda'
      Description: 'Update game Lambda function'
      CodeUri: lambdas/functions/db/update-game
      Policies:
        - Statement:
          - Effect: "Allow"
            Action:
              - 'lambda:GetLayerVersion'
            Resource:
              - !Sub 'arn:aws:lambda:*:${AWS::AccountId}:layer:*:*'
      Events:
        UpdateGame:
          Type: HttpApi
          Properties:
            ApiId: !Ref LambdaAPI
            Method: POST
            Path: /update-game
      Layers:
        - !Ref AwsServices
